version: "3.9"
services:
        postgres:
                build:
                        context: ./postgresql
                image: "postgres:15.1"
                restart: unless-stopped
                container_name: ${POSTGRES_CONTAINER_NAME}
                environment:
                        POSTGRES_DB: ${POSTGRES_DB}
                        POSTGRES_USER: ${POSTGRES_USER}
                        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
                volumes:
                        - db:/var/lib/pgsql/data
                ports:
                        - "5432:5432"

volumes:
        db:
                name: "db_volume_001"